services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_EXTRA_CLASSPATH=/custom-jars/*
      - SPARK_JARS_IVY=/opt/bitnami/spark/.ivy2
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_USER=spark
      - SPARK_AUTHENTICATE=false
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark master port
    volumes:
      - ./spark-jobs:/app/spark-jobs
      - ./jars:/custom-jars
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_EXTRA_CLASSPATH=/custom-jars/*
      - SPARK_JARS_IVY=/opt/bitnami/spark/.ivy2
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_USER=spark
      - SPARK_AUTHENTICATE=false
    depends_on:
      - spark-master
    volumes:
      - ./spark-jobs:/app/spark-jobs
      - ./jars:/custom-jars
    networks:
      - spark-net

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      
      - minio-data:/data
    networks:
      - spark-net

networks:
  spark-net:

volumes:
  minio-data: